// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_picture_perfect = "CgkI0uihsP8HEAIQBg"; // <GPGSID>
        public const string achievement_experienced_chef = "CgkI0uihsP8HEAIQCw"; // <GPGSID>
        public const string achievement_sous_chef = "CgkI0uihsP8HEAIQBw"; // <GPGSID>
        public const string leaderboard_total_points = "CgkI0uihsP8HEAIQAg"; // <GPGSID>
        public const string achievement_culinary_genius = "CgkI0uihsP8HEAIQDA"; // <GPGSID>
        public const string achievement_paint_job = "CgkI0uihsP8HEAIQDg"; // <GPGSID>
        public const string achievement_flame_broiled = "CgkI0uihsP8HEAIQBA"; // <GPGSID>
        public const string leaderboard_high_score = "CgkI0uihsP8HEAIQAQ"; // <GPGSID>
        public const string achievement_the_little_things = "CgkI0uihsP8HEAIQEA"; // <GPGSID>
        public const string achievement_surviving_the_lunch_rush = "CgkI0uihsP8HEAIQCQ"; // <GPGSID>
        public const string achievement_chef_de_cuisine = "CgkI0uihsP8HEAIQCA"; // <GPGSID>
        public const string achievement_a_new_look = "CgkI0uihsP8HEAIQEQ"; // <GPGSID>
        public const string achievement_satisfied_zombie = "CgkI0uihsP8HEAIQCg"; // <GPGSID>
        public const string achievement_golden_glover = "CgkI0uihsP8HEAIQBQ"; // <GPGSID>
        public const string achievement_all_that_power = "CgkI0uihsP8HEAIQDQ"; // <GPGSID>
        public const string achievement_the_floor_below_me = "CgkI0uihsP8HEAIQDw"; // <GPGSID>
        public const string leaderboard_longest_survival_time = "CgkI0uihsP8HEAIQAw"; // <GPGSID>

}

